# Generated by Django 3.2.7 on 2021-09-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20210921_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.PositiveIntegerField(verbose_name='год рождения'),
        ),
    ]
